### ISSUE TITLE
full migration doc

### ISSUE THREAD

**Issue by nvollmar** [apache/incubator-pekko-persistence-cassandra#32]
obvious package / class  renames
config scope renames  (i.e. akka.persistence.cassandra -> pekko.persistence.cassandra)
keyspace rename (akka -> pekko)
  - option 1: overwrite config to keep using akka keyspace
  - option 2: manual to copy keyspace to pekko (and eventually drop the akka keyspace)

**Comment by pjfanning** [comment]
relates to or a duplicate of #22

**Comment by nvollmar** [comment]
It should address the last point of #22: "and promise to provide a more detailed migration doc later"

**Comment by pjfanning** [comment]
https://pekko.apache.org/docs/pekko-persistence-cassandra/current/migrations.html seems to have info about keyspaces. @nvollmar please reopen if you think we need more work.
